In [1]:
import torch
import torch.nn as nn
from main.dataset import XrayDataset
from torch.utils.data import DataLoader
from main.transform import train_transform
from main.multimodel import Multimodel

In [2]:
csv_path = r"C:\Users\Acer\Desktop\Office\X-ray-NormalVsAbnormal\Normal-abnormal-multimodel\test.csv"
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [3]:
train_dataset = XrayDataset(img_dir='', csv_path=csv_path, transform=train_transform)
train_loader = DataLoader(train_dataset, batch_size=4, shuffle=True, num_workers=4)

In [4]:
for image, label, bbox, has_bbox in train_loader:
    image, label, bbox, has_bbox = image, label, bbox, has_bbox
    break

In [5]:
image.shape, label, bbox, has_bbox

(torch.Size([4, 3, 224, 224]),
 tensor([1., 1., 1., 0.]),
 tensor([[1293., 1927., 1857., 2394.],
         [ 605.,  310.,  937.,  410.],
         [ 773., 1366., 1717., 1630.],
         [   0.,    0.,    0.,    0.]]),
 tensor([ True,  True,  True, False]))

In [6]:
model = Multimodel().to(device)

c:\Users\Acer\anaconda3\envs\X-ray-NormalVsAbnormal\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
c:\Users\Acer\anaconda3\envs\X-ray-NormalVsAbnormal\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=DenseNet121_Weights.IMAGENET1K_V1`. You can also use `weights=DenseNet121_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


In [7]:
image = image.to(device)
label = label.to(device)
bbox  = bbox.to(device)
has_bbox = has_bbox.to(device)

In [8]:
criterian = nn.BCEWithLogitsLoss()
bbox_loss = nn.MSELoss()

In [9]:
# model

In [10]:
cls_logits, bbox_preds = model(image, has_bbox)

In [12]:
cls_logits

tensor([[-0.0687],
        [-0.0455],
        [ 0.1955],
        [ 0.3368]], grad_fn=<AddmmBackward0>)

In [13]:
bbox_preds

tensor([[ 0.2444, -0.5115,  0.1681,  0.0179],
        [ 0.1616, -0.1050, -0.0156, -0.0605],
        [ 0.1621, -0.4842, -0.1014, -0.1326],
        [ 0.0000, -0.0000,  0.0000, -0.0000]], grad_fn=<MulBackward0>)